// This file is auto-generated by Prisma. Do not edit manually.
// Run: npx prisma generate

import { PrismaClient } from '@prisma/client'

let prisma: PrismaClient

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient()
} else {
  // Avoid instantiating multiple PrismaClient instances during development
  let globalForPrisma = global as typeof globalThis & {
    prisma: PrismaClient
  }
  if (!globalForPrisma.prisma) {
    globalForPrisma.prisma = new PrismaClient()
  }
  prisma = globalForPrisma.prisma
}

export default prisma
