// STUB - replace with real implementation later

export const EVENT_TYPES = {
  SCAN_EVENT: 'SCAN_EVENT',
  LOCATION_EVENT: 'LOCATION_EVENT',
  DELIVERY_EVENT: 'DELIVERY_EVENT',
  PAYMENT_EVENT: 'PAYMENT_EVENT',
  DETECTION_EVENT: 'DETECTION_EVENT',
  GEOFENCE_EVENT: 'GEOFENCE_EVENT',
  IMAGE_CAPTURE_EVENT: 'IMAGE_CAPTURE_EVENT',
  OTP_EVENT: 'OTP_EVENT',
  WHATSAPP_EVENT: 'WHATSAPP_EVENT',
  SYNC_EVENT: 'SYNC_EVENT',
} as const;
