// Sync Event Constants
export const SYNC_EVENTS = {
  SYNC_TRIGGERED: 'SYNC_TRIGGERED',
  SYNC_STARTED: 'SYNC_STARTED',
  SYNC_COMPLETED: 'SYNC_COMPLETED',
  SYNC_FAILED: 'SYNC_FAILED',
  SYNC_PROGRESS: 'SYNC_PROGRESS',
  NETWORK_ONLINE: 'NETWORK_ONLINE',
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
} as const;
